coverage:
  status:
    project:
      default:
        enabled: yes
        target: auto
    patch:
      default:
        enabled: yes
        target: 100%

flags:
  python:
    paths:
      - python/
    carryforward: true
  javascript:
    paths:
      - javascript/
    carryforward: true

comment: false
